version: '3.8'

services:
  backend:
    image: ${DOCKER_IMAGE:-datapipe_backend:latest}
    build:
      context: .
    container_name: datapipe_backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - datapipe_data:/app/instance
      - datapipe_uploads:/app/uploads
    env_file:
      - .env

volumes:
  datapipe_data:
  datapipe_uploads:
